### PR TITLE
Feature/update mqtt3 to mqtt4

### PR DESCRIPTION
**Pull request by saschadoemer**

### CODE REVIEW

**Comment by saschadoemer** [comment]
@oliverrahner since the interface is still stable, I would just bump to the next minor version?

**Comment by oliverrahner** [comment]
Agreed!

**Review by alessandroros — APPROVED** [review]
I checked the code and it seems ok for me! Many thanks

**Comment by saschadoemer** [comment]
@Frank-Wiebeler could you add a review?

**Review by oliverrahner — APPROVED** [review]

**Pull request merged**
