### PR TITLE
+ADD: Functionality to generate an AuthorizationURL for a selfdefined…

### PR DESCRIPTION
**Pull request by Frank-Wiebeler**
… state rather than one that's provided by the library

### CODE REVIEW

**Comment by saschadoemer** [comment]
@Frank-Wiebeler The test is failing. I added an implementation to make the test work and clean the code a little.

image

**Comment by saschadoemer** [comment]
@Frank-Wiebeler Could you take a look at it?

**Review by saschadoemer — APPROVED** [review]
Changed some smaller code fragments and made the tests work.

**Review by Frank-Wiebeler — COMMENTED** [review]
Thank you for your adjustments

**Pull request merged**
